## NMS（非极大值抑制）

![NMS](./soft-NMS.jpg)

```
According to what we are discussing about NMS, please write your own code for NMS in C++ or Python.  
For c++, please finish the function:
vector<vector<float>> NMS(vector<vector<float>> lists, float thre)
{
 // lists[0:4]: x1, x2, y1, y2; lists[4]: score
}
For Python, please finish the function:
def NMS(lists, thre):
 # lists is a list. lists[0:4]: x1, x2, y1, y2; lists[4]: score
 ```

In [ ]:
import numpy as np
def NMS(dets, thresh):
    x1 = dets[:, 0]
    x2 = dets[:, 1]
    y1 = dets[:, 2]
    y2 = dets[:, 3]
    scores = dets[:, 4]
    
    areas = (x1 - x2 +1) * (y1 - y1 +2)
    order = scores.argsort()[::-1] # 按score从大到小排列返回index
    
    box_keep = []
    while order:
        max_index = order[0]
        max_box = dets[max_index] 
        box_keep.append(max_box)
        order = order[1:]
        
        inner_x1 = np.max(x1[i], x1[order[1:]])
        inner_y1 = np.max(y1[i], y1[order[1:]])
        inner_x2 = np.min(x2[i], x2[order[1:]])
        inner_y2 = np.min(y2[i], y2[order[1:]])
        
        max_box_area = areas[i]
        other_box_area = areas[order[1:]]
        inner_area = np.maximum(0., inner_x2 - inner_x1 +1) * (0., inner_y2 - inner_y1 + 1)
        
        iou = inner_area / (max_box_area + other_box_area - inner_area)
        
        order = order[iou <= thresh] # order = order[np.where(iou <= thresh)]
    return box_keep
        

def get_iou(bbox1, bbox2):
    # bbox = [x1, y1, x2, y2]
    bbox1_x1 = bbox1[0]
    bbox1_y1 = bbox1[1]
    bbox1_x2 = bbox1[2]
    bbox1_y2 = bbox1[3]
    
    bbox2_x1 = bbox2[0]
    bbox2_y1 = bbox2[1]
    bbox2_x2 = bbox2[2]
    bbox2_y2 = bbox2[4]
    
    inner_x1 = max(bbox1_x1, bbox2_x1)
    inner_y1 = max(bbox1_y1, bbox2_y1)
    inner_x2 = min(bbox1_x2, bbox2_x2)
    inner_y2 = min(bbox1_y2, bbox2_y2)
    
    bbox1_area = (bbox1_x2 - bbox1_x1 + 1) * (bbox1_y2 - bbox1_y1 + 1)
    bbox2_area = (bbox2_x2 - bbox2_x1 + 1) * (bbox2_y2 - bbox2_y1 + 1)
    inner_area = max(0, inner_x2 - inner_x1 + 1) * max(0, inner_y2 - inner_y1 + 1)
    iou = float(inner_area) / float(bbox1_area + bbox2_area - inner_area)
    return iou
    

In [26]:
import numpy as np
a = np.array([[2,1,6],
              [2,3,4],
              [3,4,5],
              [5,6,7]])
b = a.argsort()[::-1]
i = b[0]
scores = np.array([1,2,3,4])
print(a[np.where(scores<=3.)])
print(a[scores<=3])
print(np.where(scores<=3.), scores<=3)

[[2 1 6]
 [2 3 4]
 [3 4 5]]
[[2 1 6]
 [2 3 4]
 [3 4 5]]
(array([0, 1, 2], dtype=int64),) [ True  True  True False]


4